### ISSUE TITLE
Base URL?

### ISSUE THREAD

**Issue by Hitendra27** [rahulv07/project-heist#5]
What is the base URL for this api?? please?

**Comment by rahulv07** [comment]
Hi.
The base url is https://project-heist-rahulv07.vercel.app/

If you want the details of the character, you need to pass the character id.

Syntax:
https://project-heist-rahulv07.vercel.app/characters/{id}

Example:
https://project-heist-rahulv07.vercel.app/characters/1

**Comment by Hitendra27** [comment]
Hello Rahul
Thank you for your reply. The base URL is redirecting me to your GitHub page. 
I think because data is in the database. 
There is no URL for getting all the characters all at once right?

kind regards

**Comment by rahulv07** [comment]
There is no URL to get all the characters at once. You could only get one at a time.

**Comment by Hitendra27** [comment]
Ok Thanks Rahul.

**Comment by rahulv07** [comment]
Doubt cleared
